#-------------------------------
# General Site Settings

title: Spain's Angular Conference
description: THE Angular conference in Spain which is 100% community driven.
description_goal: Our goal is to have top quality content available for all, and with the help of the community, it is possible.
email: team@ngspain.com
site-name: ngSpain
date: Madrid, June 28-30 2018

social: 
  twitter-handle: '@ngSpain'
  img-url: 'assets/images/social.jpg'

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Home, url: '#'}
- {name: Speakers, url: '#speakers'}
- {name: Blog, url: '#blog'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Angular Conference ng-spain in Madrid.'
  rel-author: 'https://ngspain.com'
  rel-publisher: 'https://ngspain.com'
  twitter: 
    title: 'Community driven Angular Conference in Spain'
    description: 'An International Angular Conference created by the community for the community in sunny Spain'
    image-url: 'assets/images/social-twitter.jpg'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# Speakers Section

speakers:
- {name: Todd Motto, folder: 'todd-motto', file: 'speakers/todd-motto.html', org: 'Ultimate Angular'}
- {name: Tracy Lee, folder: 'tracy-lee', file: 'speakers/tracy-lee.html', org: 'This Dot'}
- {name: Carmen Popoviciu, folder: 'carmen-popoviciu', file: 'speakers/carmen-popoviciu.html', org: 'ING'}
- {name: Simona Cotin, folder: 'simona-cotin', file: 'speakers/simona-cotin.html', org: 'Microsoft'}
- {name: Katerina Skroumpelou, folder: 'katerina-skroumpelou', file: 'speakers/katerina-skroumpelou.html', org: 'This Dot'}

#-------------------------------
# Blog Section
blogs:
- { date: Nov 1st, title: 'Title Blog 1', text: 'This is the text for the body of blog entry 1'}
- { date: Nov 2nd, title: 'Title Blog 2', text: 'This is the text for the body of blog entry 2'}
- { date: Nov 3rd, title: 'Title Blog 3', text: 'This is the text for3rde body of blog entry 3'}

#-------------------------------
# Countdown Section

countdown:
  - { id: 'months', title: 'Months'}
  - { id: 'days', title: 'Days'}
  - { id: 'hours', title: 'Hours'}
  - { id: 'minutes', title: 'Minutes'}
  - { id: 'seconds', title: 'Seconds'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/ngSpain'}


# social network icons available: 'twitter'

